# Generated by Django 4.2.7 on 2023-11-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
